version: '3.1'
services:
  elasticsearch:
    image: "bg-elasticsearch"
    ports:
      - "9200:9200"
  cassandra:
    image: "bg-cassandra"
  graphite-aggregator-cache:
    image: "graphite-aggregator-cache"
    volumes:
      - "./volumes_graphite-aggregator-cache/conf:/conf"
  graphite-web:
    image: "graphite-web"
    ports:
      - "8080:8080"
    volumes:
      - "./volumes_graphite-web/conf:/conf"
